baseURL = 'https://danwazue.github.io/'
languageCode = 'en-us'
title = 'Daniel Nwazue'

[markup.goldmark.renderer]
  unsafe = true

[params]
  greeting  = "Hi, I'm Daniel!"
  heroText  = 'I am a <span class="highlight">Mechanical Engineering</span> student at MIT.'
  headshot  = '/images/headshot.jpg'
  email     = 'danwazue@mit.edu'
  resumeURL = '/resume.pdf'