baseURL = 'https://danwazue.github.io/'
languageCode = 'en-us'
title = 'Daniel Nwazue'

[markup.goldmark.renderer]
  unsafe = true

[params]
  greeting  = "Hi, I'm Daniel!"
  heroText  = 'I am a <span class="highlight">Mechanical Engineering</span> student at MIT.'
  headshot  = '/images/headshot.webp'
  email     = 'danwazue@mit.edu'
  resumeURL = 'https://drive.google.com/file/d/1beXQ0Ig5ZHk6MtgJaQfsIfKN72jOH8o9/view?usp=sharing'

[caches]
[caches.images]
  dir = ':cacheDir/images'
